name: CBParkour
version: "${project.version}"
description: CB's parkour plugin
depend: [Vault]
authors: [Isklar, bsquidwrd]
main: Parkour
commands:
  pk:
    aliases: [pk, cbparkour]
    description: Main command.