name: CBParkour
version: "${project.version}"
description: CB's parkour plugin
author: Isklar
depend: [Vault]
main: me.isklar.cbparkour.Parkour
commands:
  pk:
    aliases: [pk, cbparkour]
    description: Main command.