name: CBParkour
version: "${project.version}"
description: CB's parkour plugin
authors: [Isklar, bsquidwrd]
depend: [Vault]
main: com.citibuild.cbparkour.Parkour
commands:
  pk:
    aliases: [pk, cbparkour]
    description: Main command.